### ISSUE TITLE
Initializing MapboxSearchSdk in kotlin

### ISSUE THREAD

**Issue by bartekkaminski** [mapbox/mapbox-search-android-examples#14]
How to properly initialize **MapboxSearchSdk**? The documentation shows that the method as below needs the **android.app.Application** application. And now the standard used is **AppCompatActivity()**. What can you do about it?

`@kotlin.jvm.JvmStatic @kotlin.jvm.JvmOverloads public final fun initialize(application: android.app.Application, accessToken: kotlin.String, locationProvider: com.mapbox.search.location.LocationProvider, geocodingEndpointBaseUrl: kotlin.String /* = compiled code */, singleBoxSearchBaseUrl: kotlin.String /* = compiled code */, viewportProvider: com.mapbox.search.ViewportProvider? /* = compiled code */): kotlin.Unit { /* compiled code */ }`

The sample codes fail to compile due to lack of initialization MapboxSearchSdk

**Comment by DzmitryFomchyn** [comment]
@bartekkaminski you can get the application instance from any context

```
    override fun onCreate(savedInstanceState: Bundle?) {
        ...
        val app = applicationContext as Application
        ...
    }
```

Note that the `MapboxSearchSdk` should be initialized only once so it makes sense to perform initialization in the Application class.

https://github.com/mapbox/mapbox-search-android-examples/blob/main/app/src/main/java/com/mapbox/search/demo/SearchDemoApplication.kt
