### ISSUE TITLE
[QUESTION] Completed Address at SearchSuggestion

### ISSUE THREAD

**Issue by bartekkaminski** [mapbox/mapbox-search-android-examples#15]
When I execute a query with `LIMIT = 5`, I get 5 suggestions and default to `Result = suggestions.first()`

The **SearchResult** object contains very useful information as below about the address:
`address='SearchAddress(houseNumber=10, street=Polna, neighborhood=null, locality=null, postcode=10-600, place=Olsztyn, district=null, region=województwo warminsko-mazurskie, country=Polska)`

Why am I not getting the data in the **SearchSuggestion** object being returned? (although I can see that the class has a field like `public abstract val address: com.mapbox.search.result.SearchAddress?`)

When I get a list of suggestions, without specific data, the user is not able to choose the appropriate value. If there was access to data such as houseNumber, street or place (it could be displayed on the list), it would be much easier for the recipient.

In the current situation, without a proper hint, you cannot find a city located 50km from the location of the samrtphone. And finding a street in another city is out of the question.

Is there any solution to this?

**Comment by DzmitryFomchyn** [comment]
What's SDK versions you are using? Bump SDK to the latest one (https://github.com/mapbox/mapbox-search-android-examples/releases/tag/v1.0.0-beta.9).

Check please with the latest version, search suggestions also should provide addresses.

**Comment by bartekkaminski** [comment]
I updated to the latest version but no changes.

It returns when I start typing "**Pol**..."

`[SearchSuggestion(id='address.7556741916512362', name='Politechniczna', requestOptions='RequestOptions(query='Pol', options=SearchOptions(proximity=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, boundingBox=null, countries=[Country(code='pl')
    ], fuzzyMatch=null, languages=[Language(code='pl'), Language(code='en')
    ], limit=5, types=[ADDRESS
    ], requestDebounce=null, origin=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, navigationOptions=null, routeOptions=null, unsafeParameters=null, ignoreIndexableRecords=false), proximityRewritten=true, originRewritten=true, endpoint='suggest', sessionID='bc644639-a9eb-425e-a273-b4f41e60dbe3', requestContext=SearchRequestContext(apiType=GEOCODING, keyboardLocale=null, screenOrientation=PORTRAIT, responseUuid=))', descriptionText='null', distanceMeters='922.2541774751098', makiIcon='null', type='IndexableRecordItem(dataProviderName='com.mapbox.search.localProvider.history')', etaMinutes='null', isBatchResolveSupported='true', dataProviderName='com.mapbox.search.localProvider.history'), SearchSuggestion(id='address.8911215772770876', name='48 Marynarki Polskiej', requestOptions='RequestOptions(query='Pol', options=SearchOptions(proximity=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, boundingBox=null, countries=[Country(code='pl')
    ], fuzzyMatch=null, languages=[Language(code='pl'), Language(code='en')
    ], limit=5, types=[ADDRESS
    ], requestDebounce=null, origin=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, navigationOptions=null, routeOptions=null, unsafeParameters=null, ignoreIndexableRecords=false), proximityRewritten=true, originRewritten=true, endpoint='suggest', sessionID='bc644639-a9eb-425e-a273-b4f41e60dbe3', requestContext=SearchRequestContext(apiType=GEOCODING, keyboardLocale=null, screenOrientation=PORTRAIT, responseUuid=))', descriptionText='null', distanceMeters='1176.6147383133723', makiIcon='null', type='IndexableRecordItem(dataProviderName='com.mapbox.search.localProvider.history')', etaMinutes='null', isBatchResolveSupported='true', dataProviderName='com.mapbox.search.localProvider.history'), SearchSuggestion(id='address.318296250114624', name='Północna', requestOptions='RequestOptions(query='Pol', options=SearchOptions(proximity=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, boundingBox=null, countries=[Country(code='pl')
    ], fuzzyMatch=null, languages=[Language(code='pl'), Language(code='en')
    ], limit=5, types=[ADDRESS
    ], requestDebounce=null, origin=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, navigationOptions=null, routeOptions=null, unsafeParameters=null, ignoreIndexableRecords=false), proximityRewritten=true, originRewritten=true, endpoint='suggest', sessionID='bc644639-a9eb-425e-a273-b4f41e60dbe3', requestContext=SearchRequestContext(apiType=GEOCODING, keyboardLocale=null, screenOrientation=PORTRAIT, responseUuid=))', descriptionText='null', distanceMeters='3314.13106170618', makiIcon='null', type='IndexableRecordItem(dataProviderName='com.mapbox.search.localProvider.history')', etaMinutes='null', isBatchResolveSupported='true', dataProviderName='com.mapbox.search.localProvider.history'), SearchSuggestion(id='address.8733859053276918', name='Polna', requestOptions='RequestOptions(query='Pol', options=SearchOptions(proximity=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, boundingBox=null, countries=[Country(code='pl')
    ], fuzzyMatch=null, languages=[Language(code='pl'), Language(code='en')
    ], limit=5, types=[ADDRESS
    ], requestDebounce=null, origin=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, navigationOptions=null, routeOptions=null, unsafeParameters=null, ignoreIndexableRecords=false), proximityRewritten=true, originRewritten=true, endpoint='suggest', sessionID='bc644639-a9eb-425e-a273-b4f41e60dbe3', requestContext=SearchRequestContext(apiType=GEOCODING, keyboardLocale=null, screenOrientation=PORTRAIT, responseUuid=))', descriptionText='null', distanceMeters='4874.706318778866', makiIcon='null', type='IndexableRecordItem(dataProviderName='com.mapbox.search.localProvider.history')', etaMinutes='null', isBatchResolveSupported='true', dataProviderName='com.mapbox.search.localProvider.history'), SearchSuggestion(id='address.824369685760084', name='2 Polna', requestOptions='RequestOptions(query='Pol', options=SearchOptions(proximity=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, boundingBox=null, countries=[Country(code='pl')
    ], fuzzyMatch=null, languages=[Language(code='pl'), Language(code='en')
    ], limit=5, types=[ADDRESS
    ], requestDebounce=null, origin=Point{type=Point, bbox=null, coordinates=[
            18.625905,
            54.3804
        ]
    }, navigationOptions=null, routeOptions=null, unsafeParameters=null, ignoreIndexableRecords=false), proximityRewritten=true, originRewritten=true, endpoint='suggest', sessionID='bc644639-a9eb-425e-a273-b4f41e60dbe3', requestContext=SearchRequestContext(apiType=GEOCODING, keyboardLocale=null, screenOrientation=PORTRAIT, responseUuid=))', descriptionText='null', distanceMeters='6802.583740242934', makiIcon='null', type='IndexableRecordItem(dataProviderName='com.mapbox.search.localProvider.history')', etaMinutes='null', isBatchResolveSupported='true', dataProviderName='com.mapbox.search.localProvider.history')
]`

and this is what **SearchResult** looks like:

`SearchResult(id='address.7556741916512362', name='Politechniczna', address='SearchAddress(houseNumber=null, street=Politechniczna, neighborhood=null, locality=null, postcode=80-230, place=Gdańsk, district=null, region=województwo pomorskie, country=Polska)', routablePoints='null', categories='[]', makiIcon='null', coordinate='Point{type=Point, bbox=null, coordinates=[18.615631103515625, 54.37468338012695]}', types='[ADDRESS]', etaMinutes='null', metadata='null')`

Here you can see that there is address data

**MyCode:**


    val listSuggestion: MutableList<String> = ArrayList()
    searchRouteAdapter = ArrayAdapter<String>(
        this,
        android.R.layout.simple_list_item_1,
        listSuggestion
    )

    searchRouteAutoComplete.threshold = 1
    searchRouteAutoComplete.setAdapter(searchRouteAdapter)
    val languages = ArrayList<Language>()
    languages.add(Language("pl"))
    languages.add(Language("en"))

    val countries = ArrayList<Country>()
    countries.add(Country("pl"))

    val dataTypes = ArrayList<QueryType>()
    dataTypes.add(QueryType.ADDRESS)

    searchRouteAutoComplete.addTextChangedListener(object : TextWatcher {
        override fun afterTextChanged(s: Editable?) {
        }

        override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
        }

        override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
            searchRequestTask = searchEngine.search(
                s.toString(),
                SearchOptions(
                    limit = 5,
                    languages = languages,
                    countries = countries,
                    types = dataTypes
                ),
                searchCallback
            )
        }
    })

**Comment by DzmitryFomchyn** [comment]
@bartekkaminski I've just checked a similar scenario and search suggestions have an initialized address, but the address is not included in the `toString()` that's why it's not visible in your output. But you can access `SearchSuggestion.address` directly. Could you please check that?

**Comment by bartekkaminski** [comment]
@DzmitryFomchyn And I checked and you are right. ToString doesn't return the object, but it is actually there. Now it is correct. Thank you for your help

**Comment by DzmitryFomchyn** [comment]
Thanks for reporting that, we'll fix `toString()` in the following release!
