### ISSUE TITLE
[QUESTION] Styling the SearchBottomSheetView component

### ISSUE THREAD

**Issue by bartekkaminski** [mapbox/mapbox-search-android-examples#18]
Is it possible to modify the appearance of `SearchBottomSheetView`?

I mean two things:
- an upload structure (e.g. exclude categories, favorites or hotCategories)

For example, for `hotCategories` I gave `emptyList()` but it doesn't work

```
    SearchBottomSheetView.Configuration(
        collapsedStateAnchor = SearchBottomSheetView.CollapsedStateAnchor.SEARCH_BAR,
        hotCategories = emptyList(),
        favoriteTemplates = emptyList()
    )
```

I would like only a text field to be available

- component background colors, text colors etc.

**Comment by DzmitryFomchyn** [comment]
> For example, for hotCategories I gave emptyList() but it doesn't work

Could you please share full code and screenshots?

> an upload structure (e.g. exclude categories, favorites or hotCategories)

We allow modifying only the components that are included in the `Configuration` class, i.e. list of hot categories, favorites, anchor, and search options.

You can try this code:
```
        searchBottomSheetView.initializeSearch(
            savedInstanceState,
            SearchBottomSheetView.Configuration(
                collapsedStateAnchor = SearchBottomSheetView.CollapsedStateAnchor.SEARCH_BAR,
                hotCategories = emptyList(),
                favoriteTemplates = emptyList()
            )
        )
```


> component background colors, text colors etc.

Unfortunately, we don't allow that customization yet. Search SDK is in beta stage now and some customisations for the UI is in our plans.

**Comment by DzmitryFomchyn** [comment]
@bartekkaminski did you have a chance to try code example provided in a previous message?

**Comment by DzmitryFomchyn** [comment]
Hi @bartekkaminski,

We've [released](https://github.com/mapbox/mapbox-search-android-examples/releases/tag/v1.0.0-beta.12) Search SDK `v1.0.0-beta.12` which now allowes to customize UI theme.

See https://github.com/mapbox/mapbox-search-android-examples/blob/main/app/src/main/java/com/mapbox/search/sample/CustomThemeActivity.kt for more information.

We're looking forward to your feedback!

**Comment by DzmitryFomchyn** [comment]
I'm closing this issue for now because we added styling functionality. Feel free to reopen it or create a new one if you have any other questions.
