### ISSUE TITLE
Navigation and Search not working together

### ISSUE THREAD

**Issue by devpnk** [mapbox/mapbox-search-android-examples#23]
Hey!

I'm using the Mapbox Navigation Core SDK and it was working fine. Now I've added the Search UI SDK, and now I get a weird error when I start the app.
I haven't even done anything with the Search sdk, only added it to my Gradle Build file:

```
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1'
implementation "com.mapbox.navigation:core:1.5.1"
implementation "com.mapbox.search:mapbox-search-android-ui:1.0.0-beta.11"
```

The line where the crash occurs is here:
`MapboxNavigationProvider.create(navigationOptions)`

And the error is a `UnsatisfiedLinkError`:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.navigator.SkuTokenSource.finalize() (tried Java_com_mapbox_navigator_SkuTokenSource_finalize and Java_com_mapbox_navigator_SkuTokenSource_finalize__)
```

I have no idea why this is happening now, but when I remove the Search SDK from gradle and sync and the re-run, the error disappears, so it has something to do with the two of them not working together?
Do I have to set this up differently?

**Comment by friendoye** [comment]
Hi @devpnk!

Seems like dependency resolution issue. Could you declare your dependencies in the following way?

```groovy
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1'
implementation "com.mapbox.navigation:core:1.5.1"
implementation ("com.mapbox.search:mapbox-search-android-ui:1.0.0-beta.11") {
   exclude group: "com.mapbox.common"
}
```

**Comment by devpnk** [comment]
thanks! that did the trick!
