### ISSUE TITLE
Chinese application name

### ISSUE THREAD

**Issue by xie99** [mapbox/mapbox-search-android-examples#31]
Application name in Chinese will throw an exception 100% recurrence

**Comment by DzmitryFomchyn** [comment]
@xie99 could you please give more details? Where did you try to set Chinese name and what that name was?

**Comment by DzmitryFomchyn** [comment]
I've tried to change app name to Chinese and everything seems to be working fine. Feel free to reopen this issue or create a new one if you still see crashes and can provide more context: code sample, device model, logs.

<img src="https://user-images.githubusercontent.com/5161509/124144934-114a5b00-da95-11eb-8482-440fe72f08aa.gif" width=50% height=50%>
