### ISSUE TITLE
Add origin to be configurable on SearchView

### ISSUE THREAD

**Issue by lobuli** [mapbox/mapbox-search-android-examples#32]
I want to be able to change the origin point of the search. For example, if the user pans the map from one location to another. I want the origin of that to be what the map center is. I can do this by using the search core. Just wondering if there was a way to do it with the search UI.

**Comment by DzmitryFomchyn** [comment]
We allow to provide new search options for every new request in [SearchResultsView](https://docs.mapbox.com/android/search/api/ui/1.0.0-beta.14/ui/com.mapbox.search.ui.view/-search-results-view/search.html) but, unfortunately, it's not supported now in the `SearchBottomSheetView`. We'll fix this in the future releases.

**Comment by DzmitryFomchyn** [comment]
Search SDK v1.0.0-beta.15 has been released https://github.com/mapbox/mapbox-search-android-examples/releases/tag/v1.0.0-beta.15

Now you can set new options for each new request `SearchBottomSheetView.searchOptions`. We are looking forward to your feedback. Feel free to reopen this issue or create a new one if you have more questions.

**Comment by lobuli** [comment]
@DzmitryFomchyn  Getting a weird error or `New location is significantly worse than the last one, skipping update.` Can you help me understand this error?

**Comment by DzmitryFomchyn** [comment]
@lobuli The source of this error should be in the [Telemetry SDK](https://github.com/mapbox/mapbox-events-android/blob/3fb54586abbe1a19a09df73f79f9637d73a5aef3/liblocation/src/main/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImpl.java#L122) and this shouldn't cause errors in the Search SDK.

Where do you see this message (crash/logs)? Is there a full log message with stacktrace?

**Comment by lobuli** [comment]
I think that error may actually have to do with my LocationChangeListener but not sure why is failing when I changed the searchOptions. Since this works if I don't mess with the origin for the search options

**Comment by DzmitryFomchyn** [comment]
I think you can just skip this error message because it's not an error actually, it just tells you that recent location is not better than previous one, you can see that logic here https://github.com/mapbox/mapbox-events-android/blob/3fb54586abbe1a19a09df73f79f9637d73a5aef3/liblocation/src/main/java/com/mapbox/android/core/location/Utils.java#L52.

Or you can cut an issue in the [mapbox-events-android](https://github.com/mapbox/mapbox-events-android) repo and get more details.
