### ISSUE TITLE
How to set the address Format?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-search-android-examples#33]
How to set the address Format (formattedAddress) to SearchAddress.FormatStyle.Full?

search demo version : mapbox-search-android-examples-1.0.0-beta.9

**Comment by DzmitryFomchyn** [comment]
@KayHung 

Would that work for your case?
```
fun formatSearchAddress(address: SearchAddress): String? {
        return address.formattedAddress(SearchAddress.FormatStyle.Full)
}
```

Also, note that you don't have to necessarily use predefined formatting
```
fun formatSearchAddress(address: SearchAddress): String? {
        return "${address.street} ${address.houseNumber}"
}
```

**Comment by KayHung** [comment]
@DzmitryFomchyn 

```
@JvmOverloads fun formattedAddress(style: FormatStyle = FormatStyle.Medium): String?
Build address string in requested style.

```
I use searchResult.getAddress().formattedAddress() to get address, but the format is Medium
I want get the FormatStyle Full address, how can I do?

**Comment by DzmitryFomchyn** [comment]
@KayHung 

You can achieve it by passing required parameter to a function `searchResult.address?.formattedAddress(SearchAddress.FormatStyle.Full)`.

**Comment by KayHung** [comment]
@DzmitryFomchyn 
When I use Kotlin
This function is work well
searchResult.address?.formattedAddress(SearchAddress.FormatStyle.Full).
How can I get it when I use Java
results.getAddress().formattedAddress(SearchAddress.FormatStyle.Full);
I got the error, Expression expected.

**Comment by DzmitryFomchyn** [comment]
@KayHung 

```Java
@Nullable
public String format(SearchAddress searchAddress) {
    return searchAddress.formattedAddress(SearchAddress.FormatStyle.Full.INSTANCE);
}
```

**Comment by KayHung** [comment]
@DzmitryFomchyn 
Thanks, the problem is solved.
