### ISSUE TITLE
Can not get 'SearchResultType' for results returned by 'localprovider.history'

### ISSUE THREAD

**Issue by AndreasBoehm** [mapbox/mapbox-search-android-examples#37]
## Environment

- Android OS version: `all`
- Devices affected: `all`
- Search SDK Version: `1.0.0-beta.16`
- Included in project Maps SDK, Nav SDK versions if available: `none`

## Code examples

Code used to load results.
```kotlin
val query = "Reinhardstraße 7 Berlin"
val options = SearchOptions.Builder()
	.types(
		QueryType.REGION,
		QueryType.ADDRESS,
		QueryType.POI,
	)
	.build()

searchEngine.search(
	query,
	searchOptions,
	...
	)
```

## Observed behavior and steps
I am building an app with a custom search UI based on the mapbox search core SDK.

Usually we get suggestions with a `resultType` of type `SearchSuggestionType.SearchResultSuggestion`.
Based on `resultType.types` a POI can be identified and displayed accordingly.

When the same query is used multiple times the result set for `onSuggestions` changes in the `SearchSuggestionsCallback`.
The `resultType` will change to `SearchSuggestionType.IndexableRecordItem` which does not provide the field `types` that would allow me to identify a POI.
The return suggestion itself is of type `IndexableRecordSearchSuggestion` and would provide the `originalSearchResult` but this class is not visible outside of the search-core module.

## Expected behavior

All returned `resultType`s contain the `types` to allow to identify e.g. a POI.
**or** `IndexableRecordSearchSuggestion` should be changed to `public` to allow me to get `originalSearchResult`

**Comment by DzmitryFomchyn** [comment]
@AndreasBoehm thanks for the report,
Makes sense, we'll fix it in the next release.

**Comment by DzmitryFomchyn** [comment]
@AndreasBoehm Search SDK v1.0.0-beta.17 has been [released](https://github.com/mapbox/mapbox-search-android-examples/releases/tag/v1.0.0-beta.17) and it contains a fix for `SearchSuggestion` type.

Public documentation will be available soon. Let us know if you have more questions!
