### ISSUE TITLE
Failed to resolve: com.mapbox.search:mapbox-search-android-ui:1.0.0-beta.2

### ISSUE THREAD

**Issue by rhomayouni** [mapbox/mapbox-search-android-examples#5]
Android studio 4.0
Gradle  classpath "com.android.tools.build:gradle:4.0.1"
gradle-6.1.1-all.zip

i have the same error with 
implementation "com.mapbox.search:mapbox-search-android:1.0.0-beta.1"

**Comment by DzmitryFomchyn** [comment]
Make sure you have a [valid secret access token with the `Downloads:Read` scope ](https://docs.mapbox.com/android/search/overview/#configure-credentials) and [declared Mapbox Downloads API's `v2/releases/maven` endpoint](https://docs.mapbox.com/android/search/overview/#add-the-dependency).

```
maven {
      url 'https://api.mapbox.com/downloads/v2/releases/maven'
      authentication {
        basic(BasicAuthentication)
      }
      credentials {
        // Do not change the username below.
        // This should always be `mapbox` (not your username). 
        username = "mapbox"
        // Use the secret token you stored in gradle.properties as the password
        password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
      }
}
```

**Comment by DzmitryFomchyn** [comment]
I'm closing this issue. Feel free to reopen it if you are sure that your credentials are correct and you still can't resolve dependencies.
